model = "gpt-5.2-codex"
model_reasoning_effort = "medium"
sandbox_mode = "workspace-write"
approval_policy = "on-request"
project_doc_fallback_filenames = ["CLAUDE.md"]
hide_agent_reasoning = false
show_raw_agent_reasoning = true
disable_paste_burst = false
web_search = "cached"

[sandbox_workspace_write]
network_access = true

[features]
unified_exec = true
shell_snapshot = true
collab = true
steer = true

[otel]
log_user_prompt = true 
environment = "dev"
exporter = {
  otlp-grpc = {
    endpoint = "http://localhost:4317",
    headers = { "x-otlp-meta" = "abc123" }
  }
}
trace_exporter = { otlp-grpc = {
  endpoint = "http://localhost:4317",
  headers = { "x-otlp-meta" = "abc123" }
}}

[notice]
hide_full_access_warning = true

[projects]
[projects."~/Projects"]
trust_level = "trusted"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]
env = { DEFAULT_MINIMUM_TOKENS = "6000" }
